In [1]:
import pandas as pd
import numpy as np

## 2000-2026 CPI Less Housing
Source: https://fred.stlouisfed.org/series/CUUR0000SA0L2

In [2]:
inflation = pd.read_csv('../data/raw/CUUR0000SA0L2.csv')

In [3]:
inflation.head()

  observation_date  CUUR0000SA0L2
0       2000-01-01          162.3
1       2000-02-01          163.3
2       2000-03-01          164.8
3       2000-04-01          164.9
4       2000-05-01          165.1

In [4]:
#Lets rename the columns to make this easier to use

In [5]:
inflation.columns = ['observation_date', 'cpi_index']

In [6]:
#Lets also convert the observation to a datetime

In [8]:
inflation['observation_date'] = pd.to_datetime(inflation['observation_date'])

In [10]:
#Now let's get an average of monthly CPI measurements
#First let's get year
inflation['year'] = inflation['observation_date'].dt.year

In [11]:
#Now we can annualize our CPI measurements
inflation_annual = inflation.groupby(['year'])['cpi_index'].mean().reset_index()

In [12]:
inflation_annual

    year   cpi_index
0   2000  165.725000
1   2001  169.741667
2   2002  170.816667
3   2003  174.583333
4   2004  179.275000
5   2005  186.050000
6   2006  191.916667
7   2007  196.638500
8   2008  205.452500
9   2009  203.301250
10  2010  208.642583
11  2011  217.047750
12  2012  221.445833
13  2013  223.820000
14  2014  226.192000
15  2015  223.313417
16  2016  223.807333
17  2017  227.241083
18  2018  231.788583
19  2019  234.214500
20  2020  235.675500
21  2021  249.142167
22  2022  271.689500
23  2023  278.412417
24  2024  283.200417
25  2025  289.002364
26  2026  293.650000

In [13]:
# Save
inflation_annual.to_csv('../data/processed/inflation_annual_2000_2026.csv', index=False)
print('Saved!')

Saved!